import { parseMapFile } from '../lib/mapFile';
import type { ConceptMap } from '../types/map';

/**
 * Ready-made maps shipped with the app (public/esempi), to see what a good
 * map looks like or to start from one. Opening an example makes a copy.
 * The files are generated by the scripts in scripts/esempi.
 */
export interface Example {
  file: string;
  title: string;
  subject: string;
  description: string;
  icon: string;
}

export const EXAMPLES: Example[] = [
  {
    file: 'rivoluzione-francese.mappeora',
    title: 'La Rivoluzione francese',
    subject: 'Storia',
    description: 'Le cause, il 1789, le quattro fasi, le conseguenze e i protagonisti.',
    icon: '✊',
  },
];

export async function loadExample(example: Example): Promise<ConceptMap> {
  const res = await fetch(`${import.meta.env.BASE_URL}esempi/${example.file}`);
  if (!res.ok) throw new Error(`example-${res.status}`);
  return parseMapFile(await res.text());
}
