import { fold, searchTerms, stem } from '../lib/searchText';

/**
 * Fluent Emoji illustrations (Microsoft, MIT licence), searchable in Italian
 * through the Unicode CLDR names and keywords. The index is generated by
 * scripts/build-illustrations.mjs and loaded only when the picker opens.
 */
export const ILLUSTRATIONS_CREDIT = 'Illustrazioni: Fluent Emoji di Microsoft (licenza MIT).';

export interface Illustration {
  /** Path of the asset in the Fluent repository, without extension. */
  path: string;
  name: string;
  glyph: string;
}

interface Entry extends Illustration {
  nameWords: string[];
  keywordWords: string[];
  phrases: string[];
  /** The name with each word stemmed: "stella" for a search of "stelle". */
  stemmedName: string;
}

interface IndexFile {
  commit: string;
  items: { g: string; n: string; k: string[]; p: string }[];
}

/**
 * Pinned version of the Fluent repository (same as the generated index), so
 * the address of a picture never changes under an existing map.
 */
export const FLUENT_COMMIT = '1ffb34c752ecf5d402f04cfb4b392c77f57c54bc';

let index: Promise<Entry[]> | undefined;

function load(): Promise<Entry[]> {
  index ??= import('../data/illustrations.json').then(({ default: data }) => {
    const file = data as IndexFile;
    if (file.commit !== FLUENT_COMMIT) console.warn('illustrations.json: commit diverso da FLUENT_COMMIT');
    return file.items.map((i) => ({
      path: i.p,
      name: i.n,
      glyph: i.g,
      nameWords: fold(i.n).split(/\s+/),
      keywordWords: i.k.flatMap((k) => fold(k).split(/\s+/)),
      phrases: [fold(i.n), ...i.k.map(fold)],
      stemmedName: stemPhrase(fold(i.n)),
    }));
  });
  return index;
}

const stemPhrase = (phrase: string) => phrase.split(/\s+/).map(stem).join(' ');

const CDN = 'https://cdn.jsdelivr.net/gh/microsoft/fluentui-emoji';

function assetUrl(path: string, kind: '3d' | 'thumb'): string {
  const file = kind === '3d' ? `${path}.png` : `${path.replace('/3D/', '/Color/').replace('_3d', '_color')}.svg`;
  return `${CDN}@${FLUENT_COMMIT}/assets/${file.split('/').map(encodeURIComponent).join('/')}`;
}

/** The 3D image saved in maps (256 px PNG). */
export const illustrationUrl = (path: string) => assetUrl(path, '3d');
/** A light vector preview for the picker grid (a few KB each). */
export const illustrationThumbUrl = (path: string) => assetUrl(path, 'thumb');

function score(entry: Entry, phrase: string, terms: string[]): [matched: number, points: number] {
  let matched = 0;
  let points = 0;
  if (entry.phrases[0] === phrase) points += 100;
  else if (entry.stemmedName === stemPhrase(phrase)) points += 80;
  else if (entry.phrases.includes(phrase)) points += 60;
  for (const t of terms) {
    const s = stem(t);
    let best = 0;
    // "acqua" is the subject of "goccia d'acqua", less so of "pistola ad acqua".
    if (entry.nameWords.includes(t)) best = Math.max(12, 20 - 4 * (entry.nameWords.length - 1));
    // "stelle" is first of all "stella", then what has "stelle" among its keywords.
    else if (stem(entry.nameWords[0]) === s) best = 16;
    else if (entry.keywordWords.includes(t)) best = 15;
    else if (entry.nameWords.some((w) => stem(w) === s)) best = 12;
    else if (entry.keywordWords.some((w) => stem(w) === s)) best = 10;
    // No prefix matching: "chi" would find "chiesa", "cellula" "cellulare".
    if (best > 0) matched++;
    points += best;
  }
  return [matched, points];
}

/** Best matches first: concepts matching more words, then closer matches. */
export async function searchIllustrations(query: string, limit = 48): Promise<Illustration[]> {
  const entries = await load();
  const terms = searchTerms(query).map(fold);
  if (terms.length === 0) return [];
  const phrase = terms.join(' ');
  return entries
    .map((e) => ({ e, s: score(e, phrase, terms) }))
    .filter(({ s }) => s[0] > 0)
    .sort((a, b) => b.s[0] - a.s[0] || b.s[1] - a.s[1] || a.e.name.length - b.e.name.length)
    .slice(0, limit)
    .map(({ e }) => ({ path: e.path, name: e.name, glyph: e.glyph }));
}

/** Suggestions when there is nothing to search yet, in this order. */
export async function illustrationsFor(glyphs: string[]): Promise<Illustration[]> {
  const entries = await load();
  const byGlyph = new Map(entries.map((e) => [e.glyph.replace(/️/g, ''), e]));
  return glyphs
    .map((g) => byGlyph.get(g.replace(/️/g, '')))
    .filter((e): e is Entry => e !== undefined)
    .map((e) => ({ path: e.path, name: e.name, glyph: e.glyph }));
}
