import {
  ArrowLeft,
  ArrowRight,
  BookOpen,
  Brain,
  Camera,
  Check,
  CircleHelp,
  ClipboardPaste,
  Clock,
  Eye,
  FolderOpen,
  GraduationCap,
  Hand,
  ImageOff,
  ImagePlus,
  Images,
  IndentDecrease,
  IndentIncrease,
  ListTree,
  Lock,
  LockOpen,
  Map as MapIcon,
  Menu,
  Mic,
  Network,
  NotebookPen,
  Palette,
  PartyPopper,
  Pencil,
  Plus,
  Printer,
  Redo2,
  RotateCcw,
  Save,
  Scissors,
  Search,
  Share,
  SkipForward,
  Square,
  Trash2,
  Undo2,
  Volume2,
  X,
  type LucideIcon,
} from 'lucide-react';

/**
 * The icons of the commands: one family of line icons, in the colour of the
 * text. Colour belongs to the map (its concepts and their pictures), so the
 * buttons around it stay quiet. Pictures that explain a choice (templates,
 * review modes, the welcome pages) are emoji, not these.
 */
const ICONS = {
  back: ArrowLeft,
  book: BookOpen,
  brain: Brain,
  camera: Camera,
  check: Check,
  clock: Clock,
  close: X,
  edit: Pencil,
  eye: Eye,
  folder: FolderOpen,
  forward: ArrowRight,
  gallery: Images,
  graduation: GraduationCap,
  hand: Hand,
  help: CircleHelp,
  image: ImagePlus,
  'image-off': ImageOff,
  indent: IndentIncrease,
  lock: Lock,
  map: MapIcon,
  menu: Menu,
  mic: Mic,
  note: NotebookPen,
  outdent: IndentDecrease,
  outline: ListTree,
  palette: Palette,
  party: PartyPopper,
  paste: ClipboardPaste,
  plus: Plus,
  print: Printer,
  redo: Redo2,
  reset: RotateCcw,
  save: Save,
  scissors: Scissors,
  search: Search,
  share: Share,
  skip: SkipForward,
  speak: Volume2,
  stop: Square,
  tidy: Network,
  trash: Trash2,
  undo: Undo2,
  unlock: LockOpen,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

/** Sized by the font size around it (1em), so large text makes it larger too. */
export function Icon({ name, className = '' }: { name: IconName; className?: string }) {
  const Svg = ICONS[name];
  return <Svg className={`icon ${className}`} aria-hidden focusable={false} strokeWidth={2.25} />;
}
